// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nexus

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNexusSecurityUserToken(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupNexusSecurityUserTokenResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupNexusSecurityUserTokenResult
	err := ctx.Invoke("nexus:index/getNexusSecurityUserToken:GetNexusSecurityUserToken", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by GetNexusSecurityUserToken.
type LookupNexusSecurityUserTokenResult struct {
	Enabled        bool   `pulumi:"enabled"`
	Id             string `pulumi:"id"`
	ProtectContent bool   `pulumi:"protectContent"`
}
