// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nexus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNexusRepositoryYumHosted(ctx *pulumi.Context, args *LookupNexusRepositoryYumHostedArgs, opts ...pulumi.InvokeOption) (*LookupNexusRepositoryYumHostedResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupNexusRepositoryYumHostedResult
	err := ctx.Invoke("nexus:index/getNexusRepositoryYumHosted:GetNexusRepositoryYumHosted", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetNexusRepositoryYumHosted.
type LookupNexusRepositoryYumHostedArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by GetNexusRepositoryYumHosted.
type LookupNexusRepositoryYumHostedResult struct {
	Cleanups      []GetNexusRepositoryYumHostedCleanup   `pulumi:"cleanups"`
	Components    []GetNexusRepositoryYumHostedComponent `pulumi:"components"`
	DeployPolicy  string                                 `pulumi:"deployPolicy"`
	Id            string                                 `pulumi:"id"`
	Name          string                                 `pulumi:"name"`
	Online        bool                                   `pulumi:"online"`
	RepodataDepth int                                    `pulumi:"repodataDepth"`
	Storages      []GetNexusRepositoryYumHostedStorage   `pulumi:"storages"`
}

func LookupNexusRepositoryYumHostedOutput(ctx *pulumi.Context, args LookupNexusRepositoryYumHostedOutputArgs, opts ...pulumi.InvokeOption) LookupNexusRepositoryYumHostedResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupNexusRepositoryYumHostedResult, error) {
			args := v.(LookupNexusRepositoryYumHostedArgs)
			r, err := LookupNexusRepositoryYumHosted(ctx, &args, opts...)
			var s LookupNexusRepositoryYumHostedResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupNexusRepositoryYumHostedResultOutput)
}

// A collection of arguments for invoking GetNexusRepositoryYumHosted.
type LookupNexusRepositoryYumHostedOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupNexusRepositoryYumHostedOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNexusRepositoryYumHostedArgs)(nil)).Elem()
}

// A collection of values returned by GetNexusRepositoryYumHosted.
type LookupNexusRepositoryYumHostedResultOutput struct{ *pulumi.OutputState }

func (LookupNexusRepositoryYumHostedResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNexusRepositoryYumHostedResult)(nil)).Elem()
}

func (o LookupNexusRepositoryYumHostedResultOutput) ToLookupNexusRepositoryYumHostedResultOutput() LookupNexusRepositoryYumHostedResultOutput {
	return o
}

func (o LookupNexusRepositoryYumHostedResultOutput) ToLookupNexusRepositoryYumHostedResultOutputWithContext(ctx context.Context) LookupNexusRepositoryYumHostedResultOutput {
	return o
}

func (o LookupNexusRepositoryYumHostedResultOutput) Cleanups() GetNexusRepositoryYumHostedCleanupArrayOutput {
	return o.ApplyT(func(v LookupNexusRepositoryYumHostedResult) []GetNexusRepositoryYumHostedCleanup { return v.Cleanups }).(GetNexusRepositoryYumHostedCleanupArrayOutput)
}

func (o LookupNexusRepositoryYumHostedResultOutput) Components() GetNexusRepositoryYumHostedComponentArrayOutput {
	return o.ApplyT(func(v LookupNexusRepositoryYumHostedResult) []GetNexusRepositoryYumHostedComponent {
		return v.Components
	}).(GetNexusRepositoryYumHostedComponentArrayOutput)
}

func (o LookupNexusRepositoryYumHostedResultOutput) DeployPolicy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusRepositoryYumHostedResult) string { return v.DeployPolicy }).(pulumi.StringOutput)
}

func (o LookupNexusRepositoryYumHostedResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusRepositoryYumHostedResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNexusRepositoryYumHostedResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusRepositoryYumHostedResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNexusRepositoryYumHostedResultOutput) Online() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNexusRepositoryYumHostedResult) bool { return v.Online }).(pulumi.BoolOutput)
}

func (o LookupNexusRepositoryYumHostedResultOutput) RepodataDepth() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNexusRepositoryYumHostedResult) int { return v.RepodataDepth }).(pulumi.IntOutput)
}

func (o LookupNexusRepositoryYumHostedResultOutput) Storages() GetNexusRepositoryYumHostedStorageArrayOutput {
	return o.ApplyT(func(v LookupNexusRepositoryYumHostedResult) []GetNexusRepositoryYumHostedStorage { return v.Storages }).(GetNexusRepositoryYumHostedStorageArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNexusRepositoryYumHostedResultOutput{})
}
