// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nexus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNexusRoutingRule(ctx *pulumi.Context, args *LookupNexusRoutingRuleArgs, opts ...pulumi.InvokeOption) (*LookupNexusRoutingRuleResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupNexusRoutingRuleResult
	err := ctx.Invoke("nexus:index/getNexusRoutingRule:GetNexusRoutingRule", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetNexusRoutingRule.
type LookupNexusRoutingRuleArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by GetNexusRoutingRule.
type LookupNexusRoutingRuleResult struct {
	Description string   `pulumi:"description"`
	Id          string   `pulumi:"id"`
	Matchers    []string `pulumi:"matchers"`
	Mode        string   `pulumi:"mode"`
	Name        string   `pulumi:"name"`
}

func LookupNexusRoutingRuleOutput(ctx *pulumi.Context, args LookupNexusRoutingRuleOutputArgs, opts ...pulumi.InvokeOption) LookupNexusRoutingRuleResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupNexusRoutingRuleResult, error) {
			args := v.(LookupNexusRoutingRuleArgs)
			r, err := LookupNexusRoutingRule(ctx, &args, opts...)
			var s LookupNexusRoutingRuleResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupNexusRoutingRuleResultOutput)
}

// A collection of arguments for invoking GetNexusRoutingRule.
type LookupNexusRoutingRuleOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupNexusRoutingRuleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNexusRoutingRuleArgs)(nil)).Elem()
}

// A collection of values returned by GetNexusRoutingRule.
type LookupNexusRoutingRuleResultOutput struct{ *pulumi.OutputState }

func (LookupNexusRoutingRuleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNexusRoutingRuleResult)(nil)).Elem()
}

func (o LookupNexusRoutingRuleResultOutput) ToLookupNexusRoutingRuleResultOutput() LookupNexusRoutingRuleResultOutput {
	return o
}

func (o LookupNexusRoutingRuleResultOutput) ToLookupNexusRoutingRuleResultOutputWithContext(ctx context.Context) LookupNexusRoutingRuleResultOutput {
	return o
}

func (o LookupNexusRoutingRuleResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusRoutingRuleResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupNexusRoutingRuleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusRoutingRuleResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNexusRoutingRuleResultOutput) Matchers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNexusRoutingRuleResult) []string { return v.Matchers }).(pulumi.StringArrayOutput)
}

func (o LookupNexusRoutingRuleResultOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusRoutingRuleResult) string { return v.Mode }).(pulumi.StringOutput)
}

func (o LookupNexusRoutingRuleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusRoutingRuleResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNexusRoutingRuleResultOutput{})
}
