// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nexus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNexusSecurityRole(ctx *pulumi.Context, args *LookupNexusSecurityRoleArgs, opts ...pulumi.InvokeOption) (*LookupNexusSecurityRoleResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupNexusSecurityRoleResult
	err := ctx.Invoke("nexus:index/getNexusSecurityRole:GetNexusSecurityRole", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetNexusSecurityRole.
type LookupNexusSecurityRoleArgs struct {
	Roleid string `pulumi:"roleid"`
}

// A collection of values returned by GetNexusSecurityRole.
type LookupNexusSecurityRoleResult struct {
	Description string   `pulumi:"description"`
	Id          string   `pulumi:"id"`
	Name        string   `pulumi:"name"`
	Privileges  []string `pulumi:"privileges"`
	Roleid      string   `pulumi:"roleid"`
	Roles       []string `pulumi:"roles"`
}

func LookupNexusSecurityRoleOutput(ctx *pulumi.Context, args LookupNexusSecurityRoleOutputArgs, opts ...pulumi.InvokeOption) LookupNexusSecurityRoleResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupNexusSecurityRoleResult, error) {
			args := v.(LookupNexusSecurityRoleArgs)
			r, err := LookupNexusSecurityRole(ctx, &args, opts...)
			var s LookupNexusSecurityRoleResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupNexusSecurityRoleResultOutput)
}

// A collection of arguments for invoking GetNexusSecurityRole.
type LookupNexusSecurityRoleOutputArgs struct {
	Roleid pulumi.StringInput `pulumi:"roleid"`
}

func (LookupNexusSecurityRoleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNexusSecurityRoleArgs)(nil)).Elem()
}

// A collection of values returned by GetNexusSecurityRole.
type LookupNexusSecurityRoleResultOutput struct{ *pulumi.OutputState }

func (LookupNexusSecurityRoleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNexusSecurityRoleResult)(nil)).Elem()
}

func (o LookupNexusSecurityRoleResultOutput) ToLookupNexusSecurityRoleResultOutput() LookupNexusSecurityRoleResultOutput {
	return o
}

func (o LookupNexusSecurityRoleResultOutput) ToLookupNexusSecurityRoleResultOutputWithContext(ctx context.Context) LookupNexusSecurityRoleResultOutput {
	return o
}

func (o LookupNexusSecurityRoleResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusSecurityRoleResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupNexusSecurityRoleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusSecurityRoleResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNexusSecurityRoleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusSecurityRoleResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNexusSecurityRoleResultOutput) Privileges() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNexusSecurityRoleResult) []string { return v.Privileges }).(pulumi.StringArrayOutput)
}

func (o LookupNexusSecurityRoleResultOutput) Roleid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusSecurityRoleResult) string { return v.Roleid }).(pulumi.StringOutput)
}

func (o LookupNexusSecurityRoleResultOutput) Roles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNexusSecurityRoleResult) []string { return v.Roles }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNexusSecurityRoleResultOutput{})
}
