// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nexus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNexusRepositoryAptHosted(ctx *pulumi.Context, args *LookupNexusRepositoryAptHostedArgs, opts ...pulumi.InvokeOption) (*LookupNexusRepositoryAptHostedResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupNexusRepositoryAptHostedResult
	err := ctx.Invoke("nexus:index/getNexusRepositoryAptHosted:GetNexusRepositoryAptHosted", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetNexusRepositoryAptHosted.
type LookupNexusRepositoryAptHostedArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by GetNexusRepositoryAptHosted.
type LookupNexusRepositoryAptHostedResult struct {
	Cleanups     []GetNexusRepositoryAptHostedCleanup   `pulumi:"cleanups"`
	Components   []GetNexusRepositoryAptHostedComponent `pulumi:"components"`
	Distribution string                                 `pulumi:"distribution"`
	Id           string                                 `pulumi:"id"`
	Name         string                                 `pulumi:"name"`
	Online       bool                                   `pulumi:"online"`
	Storages     []GetNexusRepositoryAptHostedStorage   `pulumi:"storages"`
}

func LookupNexusRepositoryAptHostedOutput(ctx *pulumi.Context, args LookupNexusRepositoryAptHostedOutputArgs, opts ...pulumi.InvokeOption) LookupNexusRepositoryAptHostedResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupNexusRepositoryAptHostedResult, error) {
			args := v.(LookupNexusRepositoryAptHostedArgs)
			r, err := LookupNexusRepositoryAptHosted(ctx, &args, opts...)
			var s LookupNexusRepositoryAptHostedResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupNexusRepositoryAptHostedResultOutput)
}

// A collection of arguments for invoking GetNexusRepositoryAptHosted.
type LookupNexusRepositoryAptHostedOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupNexusRepositoryAptHostedOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNexusRepositoryAptHostedArgs)(nil)).Elem()
}

// A collection of values returned by GetNexusRepositoryAptHosted.
type LookupNexusRepositoryAptHostedResultOutput struct{ *pulumi.OutputState }

func (LookupNexusRepositoryAptHostedResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNexusRepositoryAptHostedResult)(nil)).Elem()
}

func (o LookupNexusRepositoryAptHostedResultOutput) ToLookupNexusRepositoryAptHostedResultOutput() LookupNexusRepositoryAptHostedResultOutput {
	return o
}

func (o LookupNexusRepositoryAptHostedResultOutput) ToLookupNexusRepositoryAptHostedResultOutputWithContext(ctx context.Context) LookupNexusRepositoryAptHostedResultOutput {
	return o
}

func (o LookupNexusRepositoryAptHostedResultOutput) Cleanups() GetNexusRepositoryAptHostedCleanupArrayOutput {
	return o.ApplyT(func(v LookupNexusRepositoryAptHostedResult) []GetNexusRepositoryAptHostedCleanup { return v.Cleanups }).(GetNexusRepositoryAptHostedCleanupArrayOutput)
}

func (o LookupNexusRepositoryAptHostedResultOutput) Components() GetNexusRepositoryAptHostedComponentArrayOutput {
	return o.ApplyT(func(v LookupNexusRepositoryAptHostedResult) []GetNexusRepositoryAptHostedComponent {
		return v.Components
	}).(GetNexusRepositoryAptHostedComponentArrayOutput)
}

func (o LookupNexusRepositoryAptHostedResultOutput) Distribution() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusRepositoryAptHostedResult) string { return v.Distribution }).(pulumi.StringOutput)
}

func (o LookupNexusRepositoryAptHostedResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusRepositoryAptHostedResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNexusRepositoryAptHostedResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNexusRepositoryAptHostedResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNexusRepositoryAptHostedResultOutput) Online() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNexusRepositoryAptHostedResult) bool { return v.Online }).(pulumi.BoolOutput)
}

func (o LookupNexusRepositoryAptHostedResultOutput) Storages() GetNexusRepositoryAptHostedStorageArrayOutput {
	return o.ApplyT(func(v LookupNexusRepositoryAptHostedResult) []GetNexusRepositoryAptHostedStorage { return v.Storages }).(GetNexusRepositoryAptHostedStorageArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNexusRepositoryAptHostedResultOutput{})
}
