// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nexus

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNexusAnonymous(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupNexusAnonymousResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupNexusAnonymousResult
	err := ctx.Invoke("nexus:index/getNexusAnonymous:GetNexusAnonymous", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by GetNexusAnonymous.
type LookupNexusAnonymousResult struct {
	Enabled   bool   `pulumi:"enabled"`
	Id        string `pulumi:"id"`
	RealmName string `pulumi:"realmName"`
	UserId    string `pulumi:"userId"`
}
