// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nexus

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNexusSecurityLdap(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupNexusSecurityLdapResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupNexusSecurityLdapResult
	err := ctx.Invoke("nexus:index/getNexusSecurityLdap:GetNexusSecurityLdap", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by GetNexusSecurityLdap.
type LookupNexusSecurityLdapResult struct {
	Id    string                     `pulumi:"id"`
	Ldaps []GetNexusSecurityLdapLdap `pulumi:"ldaps"`
}
