// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nexus

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NexusRepositoryMavenHosted struct {
	pulumi.CustomResourceState

	// Cleanup policies
	Cleanups NexusRepositoryMavenHostedCleanupArrayOutput `pulumi:"cleanups"`
	// Component configuration for the hosted repository
	Component NexusRepositoryMavenHostedComponentOutput `pulumi:"component"`
	// Maven contains additional data of maven repository
	Maven NexusRepositoryMavenHostedMavenOutput `pulumi:"maven"`
	// A unique identifier for this repository
	Name pulumi.StringOutput `pulumi:"name"`
	// Whether this repository accepts incoming requests
	Online pulumi.BoolPtrOutput `pulumi:"online"`
	// The storage configuration of the repository
	Storage NexusRepositoryMavenHostedStorageOutput `pulumi:"storage"`
}

// NewNexusRepositoryMavenHosted registers a new resource with the given unique name, arguments, and options.
func NewNexusRepositoryMavenHosted(ctx *pulumi.Context,
	name string, args *NexusRepositoryMavenHostedArgs, opts ...pulumi.ResourceOption) (*NexusRepositoryMavenHosted, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Maven == nil {
		return nil, errors.New("invalid value for required argument 'Maven'")
	}
	if args.Storage == nil {
		return nil, errors.New("invalid value for required argument 'Storage'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource NexusRepositoryMavenHosted
	err := ctx.RegisterResource("nexus:index/nexusRepositoryMavenHosted:NexusRepositoryMavenHosted", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNexusRepositoryMavenHosted gets an existing NexusRepositoryMavenHosted resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNexusRepositoryMavenHosted(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NexusRepositoryMavenHostedState, opts ...pulumi.ResourceOption) (*NexusRepositoryMavenHosted, error) {
	var resource NexusRepositoryMavenHosted
	err := ctx.ReadResource("nexus:index/nexusRepositoryMavenHosted:NexusRepositoryMavenHosted", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NexusRepositoryMavenHosted resources.
type nexusRepositoryMavenHostedState struct {
	// Cleanup policies
	Cleanups []NexusRepositoryMavenHostedCleanup `pulumi:"cleanups"`
	// Component configuration for the hosted repository
	Component *NexusRepositoryMavenHostedComponent `pulumi:"component"`
	// Maven contains additional data of maven repository
	Maven *NexusRepositoryMavenHostedMaven `pulumi:"maven"`
	// A unique identifier for this repository
	Name *string `pulumi:"name"`
	// Whether this repository accepts incoming requests
	Online *bool `pulumi:"online"`
	// The storage configuration of the repository
	Storage *NexusRepositoryMavenHostedStorage `pulumi:"storage"`
}

type NexusRepositoryMavenHostedState struct {
	// Cleanup policies
	Cleanups NexusRepositoryMavenHostedCleanupArrayInput
	// Component configuration for the hosted repository
	Component NexusRepositoryMavenHostedComponentPtrInput
	// Maven contains additional data of maven repository
	Maven NexusRepositoryMavenHostedMavenPtrInput
	// A unique identifier for this repository
	Name pulumi.StringPtrInput
	// Whether this repository accepts incoming requests
	Online pulumi.BoolPtrInput
	// The storage configuration of the repository
	Storage NexusRepositoryMavenHostedStoragePtrInput
}

func (NexusRepositoryMavenHostedState) ElementType() reflect.Type {
	return reflect.TypeOf((*nexusRepositoryMavenHostedState)(nil)).Elem()
}

type nexusRepositoryMavenHostedArgs struct {
	// Cleanup policies
	Cleanups []NexusRepositoryMavenHostedCleanup `pulumi:"cleanups"`
	// Component configuration for the hosted repository
	Component *NexusRepositoryMavenHostedComponent `pulumi:"component"`
	// Maven contains additional data of maven repository
	Maven NexusRepositoryMavenHostedMaven `pulumi:"maven"`
	// A unique identifier for this repository
	Name *string `pulumi:"name"`
	// Whether this repository accepts incoming requests
	Online *bool `pulumi:"online"`
	// The storage configuration of the repository
	Storage NexusRepositoryMavenHostedStorage `pulumi:"storage"`
}

// The set of arguments for constructing a NexusRepositoryMavenHosted resource.
type NexusRepositoryMavenHostedArgs struct {
	// Cleanup policies
	Cleanups NexusRepositoryMavenHostedCleanupArrayInput
	// Component configuration for the hosted repository
	Component NexusRepositoryMavenHostedComponentPtrInput
	// Maven contains additional data of maven repository
	Maven NexusRepositoryMavenHostedMavenInput
	// A unique identifier for this repository
	Name pulumi.StringPtrInput
	// Whether this repository accepts incoming requests
	Online pulumi.BoolPtrInput
	// The storage configuration of the repository
	Storage NexusRepositoryMavenHostedStorageInput
}

func (NexusRepositoryMavenHostedArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*nexusRepositoryMavenHostedArgs)(nil)).Elem()
}

type NexusRepositoryMavenHostedInput interface {
	pulumi.Input

	ToNexusRepositoryMavenHostedOutput() NexusRepositoryMavenHostedOutput
	ToNexusRepositoryMavenHostedOutputWithContext(ctx context.Context) NexusRepositoryMavenHostedOutput
}

func (*NexusRepositoryMavenHosted) ElementType() reflect.Type {
	return reflect.TypeOf((**NexusRepositoryMavenHosted)(nil)).Elem()
}

func (i *NexusRepositoryMavenHosted) ToNexusRepositoryMavenHostedOutput() NexusRepositoryMavenHostedOutput {
	return i.ToNexusRepositoryMavenHostedOutputWithContext(context.Background())
}

func (i *NexusRepositoryMavenHosted) ToNexusRepositoryMavenHostedOutputWithContext(ctx context.Context) NexusRepositoryMavenHostedOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NexusRepositoryMavenHostedOutput)
}

// NexusRepositoryMavenHostedArrayInput is an input type that accepts NexusRepositoryMavenHostedArray and NexusRepositoryMavenHostedArrayOutput values.
// You can construct a concrete instance of `NexusRepositoryMavenHostedArrayInput` via:
//
//          NexusRepositoryMavenHostedArray{ NexusRepositoryMavenHostedArgs{...} }
type NexusRepositoryMavenHostedArrayInput interface {
	pulumi.Input

	ToNexusRepositoryMavenHostedArrayOutput() NexusRepositoryMavenHostedArrayOutput
	ToNexusRepositoryMavenHostedArrayOutputWithContext(context.Context) NexusRepositoryMavenHostedArrayOutput
}

type NexusRepositoryMavenHostedArray []NexusRepositoryMavenHostedInput

func (NexusRepositoryMavenHostedArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NexusRepositoryMavenHosted)(nil)).Elem()
}

func (i NexusRepositoryMavenHostedArray) ToNexusRepositoryMavenHostedArrayOutput() NexusRepositoryMavenHostedArrayOutput {
	return i.ToNexusRepositoryMavenHostedArrayOutputWithContext(context.Background())
}

func (i NexusRepositoryMavenHostedArray) ToNexusRepositoryMavenHostedArrayOutputWithContext(ctx context.Context) NexusRepositoryMavenHostedArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NexusRepositoryMavenHostedArrayOutput)
}

// NexusRepositoryMavenHostedMapInput is an input type that accepts NexusRepositoryMavenHostedMap and NexusRepositoryMavenHostedMapOutput values.
// You can construct a concrete instance of `NexusRepositoryMavenHostedMapInput` via:
//
//          NexusRepositoryMavenHostedMap{ "key": NexusRepositoryMavenHostedArgs{...} }
type NexusRepositoryMavenHostedMapInput interface {
	pulumi.Input

	ToNexusRepositoryMavenHostedMapOutput() NexusRepositoryMavenHostedMapOutput
	ToNexusRepositoryMavenHostedMapOutputWithContext(context.Context) NexusRepositoryMavenHostedMapOutput
}

type NexusRepositoryMavenHostedMap map[string]NexusRepositoryMavenHostedInput

func (NexusRepositoryMavenHostedMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NexusRepositoryMavenHosted)(nil)).Elem()
}

func (i NexusRepositoryMavenHostedMap) ToNexusRepositoryMavenHostedMapOutput() NexusRepositoryMavenHostedMapOutput {
	return i.ToNexusRepositoryMavenHostedMapOutputWithContext(context.Background())
}

func (i NexusRepositoryMavenHostedMap) ToNexusRepositoryMavenHostedMapOutputWithContext(ctx context.Context) NexusRepositoryMavenHostedMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NexusRepositoryMavenHostedMapOutput)
}

type NexusRepositoryMavenHostedOutput struct{ *pulumi.OutputState }

func (NexusRepositoryMavenHostedOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NexusRepositoryMavenHosted)(nil)).Elem()
}

func (o NexusRepositoryMavenHostedOutput) ToNexusRepositoryMavenHostedOutput() NexusRepositoryMavenHostedOutput {
	return o
}

func (o NexusRepositoryMavenHostedOutput) ToNexusRepositoryMavenHostedOutputWithContext(ctx context.Context) NexusRepositoryMavenHostedOutput {
	return o
}

// Cleanup policies
func (o NexusRepositoryMavenHostedOutput) Cleanups() NexusRepositoryMavenHostedCleanupArrayOutput {
	return o.ApplyT(func(v *NexusRepositoryMavenHosted) NexusRepositoryMavenHostedCleanupArrayOutput { return v.Cleanups }).(NexusRepositoryMavenHostedCleanupArrayOutput)
}

// Component configuration for the hosted repository
func (o NexusRepositoryMavenHostedOutput) Component() NexusRepositoryMavenHostedComponentOutput {
	return o.ApplyT(func(v *NexusRepositoryMavenHosted) NexusRepositoryMavenHostedComponentOutput { return v.Component }).(NexusRepositoryMavenHostedComponentOutput)
}

// Maven contains additional data of maven repository
func (o NexusRepositoryMavenHostedOutput) Maven() NexusRepositoryMavenHostedMavenOutput {
	return o.ApplyT(func(v *NexusRepositoryMavenHosted) NexusRepositoryMavenHostedMavenOutput { return v.Maven }).(NexusRepositoryMavenHostedMavenOutput)
}

// A unique identifier for this repository
func (o NexusRepositoryMavenHostedOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NexusRepositoryMavenHosted) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Whether this repository accepts incoming requests
func (o NexusRepositoryMavenHostedOutput) Online() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NexusRepositoryMavenHosted) pulumi.BoolPtrOutput { return v.Online }).(pulumi.BoolPtrOutput)
}

// The storage configuration of the repository
func (o NexusRepositoryMavenHostedOutput) Storage() NexusRepositoryMavenHostedStorageOutput {
	return o.ApplyT(func(v *NexusRepositoryMavenHosted) NexusRepositoryMavenHostedStorageOutput { return v.Storage }).(NexusRepositoryMavenHostedStorageOutput)
}

type NexusRepositoryMavenHostedArrayOutput struct{ *pulumi.OutputState }

func (NexusRepositoryMavenHostedArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NexusRepositoryMavenHosted)(nil)).Elem()
}

func (o NexusRepositoryMavenHostedArrayOutput) ToNexusRepositoryMavenHostedArrayOutput() NexusRepositoryMavenHostedArrayOutput {
	return o
}

func (o NexusRepositoryMavenHostedArrayOutput) ToNexusRepositoryMavenHostedArrayOutputWithContext(ctx context.Context) NexusRepositoryMavenHostedArrayOutput {
	return o
}

func (o NexusRepositoryMavenHostedArrayOutput) Index(i pulumi.IntInput) NexusRepositoryMavenHostedOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NexusRepositoryMavenHosted {
		return vs[0].([]*NexusRepositoryMavenHosted)[vs[1].(int)]
	}).(NexusRepositoryMavenHostedOutput)
}

type NexusRepositoryMavenHostedMapOutput struct{ *pulumi.OutputState }

func (NexusRepositoryMavenHostedMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NexusRepositoryMavenHosted)(nil)).Elem()
}

func (o NexusRepositoryMavenHostedMapOutput) ToNexusRepositoryMavenHostedMapOutput() NexusRepositoryMavenHostedMapOutput {
	return o
}

func (o NexusRepositoryMavenHostedMapOutput) ToNexusRepositoryMavenHostedMapOutputWithContext(ctx context.Context) NexusRepositoryMavenHostedMapOutput {
	return o
}

func (o NexusRepositoryMavenHostedMapOutput) MapIndex(k pulumi.StringInput) NexusRepositoryMavenHostedOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NexusRepositoryMavenHosted {
		return vs[0].(map[string]*NexusRepositoryMavenHosted)[vs[1].(string)]
	}).(NexusRepositoryMavenHostedOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NexusRepositoryMavenHostedInput)(nil)).Elem(), &NexusRepositoryMavenHosted{})
	pulumi.RegisterInputType(reflect.TypeOf((*NexusRepositoryMavenHostedArrayInput)(nil)).Elem(), NexusRepositoryMavenHostedArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NexusRepositoryMavenHostedMapInput)(nil)).Elem(), NexusRepositoryMavenHostedMap{})
	pulumi.RegisterOutputType(NexusRepositoryMavenHostedOutput{})
	pulumi.RegisterOutputType(NexusRepositoryMavenHostedArrayOutput{})
	pulumi.RegisterOutputType(NexusRepositoryMavenHostedMapOutput{})
}
