// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    public static class GetNexusSecurityLdap
    {
        public static Task<GetNexusSecurityLdapResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNexusSecurityLdapResult>("nexus:index/getNexusSecurityLdap:GetNexusSecurityLdap", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetNexusSecurityLdapResult
    {
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetNexusSecurityLdapLdapResult> Ldaps;

        [OutputConstructor]
        private GetNexusSecurityLdapResult(
            string id,

            ImmutableArray<Outputs.GetNexusSecurityLdapLdapResult> ldaps)
        {
            Id = id;
            Ldaps = ldaps;
        }
    }
}
