// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    public static class GetNexusRepositoryYumGroup
    {
        public static Task<GetNexusRepositoryYumGroupResult> InvokeAsync(GetNexusRepositoryYumGroupArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNexusRepositoryYumGroupResult>("nexus:index/getNexusRepositoryYumGroup:GetNexusRepositoryYumGroup", args ?? new GetNexusRepositoryYumGroupArgs(), options.WithDefaults());

        public static Output<GetNexusRepositoryYumGroupResult> Invoke(GetNexusRepositoryYumGroupInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetNexusRepositoryYumGroupResult>("nexus:index/getNexusRepositoryYumGroup:GetNexusRepositoryYumGroup", args ?? new GetNexusRepositoryYumGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNexusRepositoryYumGroupArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetNexusRepositoryYumGroupArgs()
        {
        }
    }

    public sealed class GetNexusRepositoryYumGroupInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetNexusRepositoryYumGroupInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetNexusRepositoryYumGroupResult
    {
        public readonly ImmutableArray<Outputs.GetNexusRepositoryYumGroupGroupResult> Groups;
        public readonly string Id;
        public readonly string Name;
        public readonly bool Online;
        public readonly ImmutableArray<Outputs.GetNexusRepositoryYumGroupStorageResult> Storages;
        public readonly ImmutableArray<Outputs.GetNexusRepositoryYumGroupYumSigningResult> YumSignings;

        [OutputConstructor]
        private GetNexusRepositoryYumGroupResult(
            ImmutableArray<Outputs.GetNexusRepositoryYumGroupGroupResult> groups,

            string id,

            string name,

            bool online,

            ImmutableArray<Outputs.GetNexusRepositoryYumGroupStorageResult> storages,

            ImmutableArray<Outputs.GetNexusRepositoryYumGroupYumSigningResult> yumSignings)
        {
            Groups = groups;
            Id = id;
            Name = name;
            Online = online;
            Storages = storages;
            YumSignings = yumSignings;
        }
    }
}
