// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    public static class GetNexusSecurityRole
    {
        public static Task<GetNexusSecurityRoleResult> InvokeAsync(GetNexusSecurityRoleArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNexusSecurityRoleResult>("nexus:index/getNexusSecurityRole:GetNexusSecurityRole", args ?? new GetNexusSecurityRoleArgs(), options.WithDefaults());

        public static Output<GetNexusSecurityRoleResult> Invoke(GetNexusSecurityRoleInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetNexusSecurityRoleResult>("nexus:index/getNexusSecurityRole:GetNexusSecurityRole", args ?? new GetNexusSecurityRoleInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNexusSecurityRoleArgs : Pulumi.InvokeArgs
    {
        [Input("roleid", required: true)]
        public string Roleid { get; set; } = null!;

        public GetNexusSecurityRoleArgs()
        {
        }
    }

    public sealed class GetNexusSecurityRoleInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("roleid", required: true)]
        public Input<string> Roleid { get; set; } = null!;

        public GetNexusSecurityRoleInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetNexusSecurityRoleResult
    {
        public readonly string Description;
        public readonly string Id;
        public readonly string Name;
        public readonly ImmutableArray<string> Privileges;
        public readonly string Roleid;
        public readonly ImmutableArray<string> Roles;

        [OutputConstructor]
        private GetNexusSecurityRoleResult(
            string description,

            string id,

            string name,

            ImmutableArray<string> privileges,

            string roleid,

            ImmutableArray<string> roles)
        {
            Description = description;
            Id = id;
            Name = name;
            Privileges = privileges;
            Roleid = roleid;
            Roles = roles;
        }
    }
}
