// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    public static class GetNexusSecurityUser
    {
        public static Task<GetNexusSecurityUserResult> InvokeAsync(GetNexusSecurityUserArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNexusSecurityUserResult>("nexus:index/getNexusSecurityUser:GetNexusSecurityUser", args ?? new GetNexusSecurityUserArgs(), options.WithDefaults());

        public static Output<GetNexusSecurityUserResult> Invoke(GetNexusSecurityUserInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetNexusSecurityUserResult>("nexus:index/getNexusSecurityUser:GetNexusSecurityUser", args ?? new GetNexusSecurityUserInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNexusSecurityUserArgs : Pulumi.InvokeArgs
    {
        [Input("userid", required: true)]
        public string Userid { get; set; } = null!;

        public GetNexusSecurityUserArgs()
        {
        }
    }

    public sealed class GetNexusSecurityUserInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("userid", required: true)]
        public Input<string> Userid { get; set; } = null!;

        public GetNexusSecurityUserInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetNexusSecurityUserResult
    {
        public readonly string Email;
        public readonly string Firstname;
        public readonly string Id;
        public readonly string Lastname;
        public readonly ImmutableArray<string> Roles;
        public readonly string Status;
        public readonly string Userid;

        [OutputConstructor]
        private GetNexusSecurityUserResult(
            string email,

            string firstname,

            string id,

            string lastname,

            ImmutableArray<string> roles,

            string status,

            string userid)
        {
            Email = email;
            Firstname = firstname;
            Id = id;
            Lastname = lastname;
            Roles = roles;
            Status = status;
            Userid = userid;
        }
    }
}
