// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    public static class GetNexusPrivileges
    {
        public static Task<GetNexusPrivilegesResult> InvokeAsync(GetNexusPrivilegesArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNexusPrivilegesResult>("nexus:index/getNexusPrivileges:GetNexusPrivileges", args ?? new GetNexusPrivilegesArgs(), options.WithDefaults());

        public static Output<GetNexusPrivilegesResult> Invoke(GetNexusPrivilegesInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetNexusPrivilegesResult>("nexus:index/getNexusPrivileges:GetNexusPrivileges", args ?? new GetNexusPrivilegesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNexusPrivilegesArgs : Pulumi.InvokeArgs
    {
        [Input("domain")]
        public string? Domain { get; set; }

        [Input("format")]
        public string? Format { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("repository")]
        public string? Repository { get; set; }

        [Input("type")]
        public string? Type { get; set; }

        public GetNexusPrivilegesArgs()
        {
        }
    }

    public sealed class GetNexusPrivilegesInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("domain")]
        public Input<string>? Domain { get; set; }

        [Input("format")]
        public Input<string>? Format { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("repository")]
        public Input<string>? Repository { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public GetNexusPrivilegesInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetNexusPrivilegesResult
    {
        public readonly string? Domain;
        public readonly string? Format;
        public readonly string Id;
        public readonly string? Name;
        public readonly ImmutableArray<Outputs.GetNexusPrivilegesPrivilegeResult> Privileges;
        public readonly string? Repository;
        public readonly string? Type;

        [OutputConstructor]
        private GetNexusPrivilegesResult(
            string? domain,

            string? format,

            string id,

            string? name,

            ImmutableArray<Outputs.GetNexusPrivilegesPrivilegeResult> privileges,

            string? repository,

            string? type)
        {
            Domain = domain;
            Format = format;
            Id = id;
            Name = name;
            Privileges = privileges;
            Repository = repository;
            Type = type;
        }
    }
}
