// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    public static class GetNexusRepositoryAptHosted
    {
        public static Task<GetNexusRepositoryAptHostedResult> InvokeAsync(GetNexusRepositoryAptHostedArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNexusRepositoryAptHostedResult>("nexus:index/getNexusRepositoryAptHosted:GetNexusRepositoryAptHosted", args ?? new GetNexusRepositoryAptHostedArgs(), options.WithDefaults());

        public static Output<GetNexusRepositoryAptHostedResult> Invoke(GetNexusRepositoryAptHostedInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetNexusRepositoryAptHostedResult>("nexus:index/getNexusRepositoryAptHosted:GetNexusRepositoryAptHosted", args ?? new GetNexusRepositoryAptHostedInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNexusRepositoryAptHostedArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetNexusRepositoryAptHostedArgs()
        {
        }
    }

    public sealed class GetNexusRepositoryAptHostedInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetNexusRepositoryAptHostedInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetNexusRepositoryAptHostedResult
    {
        public readonly ImmutableArray<Outputs.GetNexusRepositoryAptHostedCleanupResult> Cleanups;
        public readonly ImmutableArray<Outputs.GetNexusRepositoryAptHostedComponentResult> Components;
        public readonly string Distribution;
        public readonly string Id;
        public readonly string Name;
        public readonly bool Online;
        public readonly ImmutableArray<Outputs.GetNexusRepositoryAptHostedStorageResult> Storages;

        [OutputConstructor]
        private GetNexusRepositoryAptHostedResult(
            ImmutableArray<Outputs.GetNexusRepositoryAptHostedCleanupResult> cleanups,

            ImmutableArray<Outputs.GetNexusRepositoryAptHostedComponentResult> components,

            string distribution,

            string id,

            string name,

            bool online,

            ImmutableArray<Outputs.GetNexusRepositoryAptHostedStorageResult> storages)
        {
            Cleanups = cleanups;
            Components = components;
            Distribution = distribution;
            Id = id;
            Name = name;
            Online = online;
            Storages = storages;
        }
    }
}
