// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    [NexusResourceType("nexus:index/nexusRepositoryMavenHosted:NexusRepositoryMavenHosted")]
    public partial class NexusRepositoryMavenHosted : Pulumi.CustomResource
    {
        /// <summary>
        /// Cleanup policies
        /// </summary>
        [Output("cleanups")]
        public Output<ImmutableArray<Outputs.NexusRepositoryMavenHostedCleanup>> Cleanups { get; private set; } = null!;

        /// <summary>
        /// Component configuration for the hosted repository
        /// </summary>
        [Output("component")]
        public Output<Outputs.NexusRepositoryMavenHostedComponent> Component { get; private set; } = null!;

        /// <summary>
        /// Maven contains additional data of maven repository
        /// </summary>
        [Output("maven")]
        public Output<Outputs.NexusRepositoryMavenHostedMaven> Maven { get; private set; } = null!;

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Output("online")]
        public Output<bool?> Online { get; private set; } = null!;

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Output("storage")]
        public Output<Outputs.NexusRepositoryMavenHostedStorage> Storage { get; private set; } = null!;


        /// <summary>
        /// Create a NexusRepositoryMavenHosted resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NexusRepositoryMavenHosted(string name, NexusRepositoryMavenHostedArgs args, CustomResourceOptions? options = null)
            : base("nexus:index/nexusRepositoryMavenHosted:NexusRepositoryMavenHosted", name, args ?? new NexusRepositoryMavenHostedArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NexusRepositoryMavenHosted(string name, Input<string> id, NexusRepositoryMavenHostedState? state = null, CustomResourceOptions? options = null)
            : base("nexus:index/nexusRepositoryMavenHosted:NexusRepositoryMavenHosted", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/SimCubeLtd/pulumi-nexus/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NexusRepositoryMavenHosted resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NexusRepositoryMavenHosted Get(string name, Input<string> id, NexusRepositoryMavenHostedState? state = null, CustomResourceOptions? options = null)
        {
            return new NexusRepositoryMavenHosted(name, id, state, options);
        }
    }

    public sealed class NexusRepositoryMavenHostedArgs : Pulumi.ResourceArgs
    {
        [Input("cleanups")]
        private InputList<Inputs.NexusRepositoryMavenHostedCleanupArgs>? _cleanups;

        /// <summary>
        /// Cleanup policies
        /// </summary>
        public InputList<Inputs.NexusRepositoryMavenHostedCleanupArgs> Cleanups
        {
            get => _cleanups ?? (_cleanups = new InputList<Inputs.NexusRepositoryMavenHostedCleanupArgs>());
            set => _cleanups = value;
        }

        /// <summary>
        /// Component configuration for the hosted repository
        /// </summary>
        [Input("component")]
        public Input<Inputs.NexusRepositoryMavenHostedComponentArgs>? Component { get; set; }

        /// <summary>
        /// Maven contains additional data of maven repository
        /// </summary>
        [Input("maven", required: true)]
        public Input<Inputs.NexusRepositoryMavenHostedMavenArgs> Maven { get; set; } = null!;

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Input("online")]
        public Input<bool>? Online { get; set; }

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Input("storage", required: true)]
        public Input<Inputs.NexusRepositoryMavenHostedStorageArgs> Storage { get; set; } = null!;

        public NexusRepositoryMavenHostedArgs()
        {
        }
    }

    public sealed class NexusRepositoryMavenHostedState : Pulumi.ResourceArgs
    {
        [Input("cleanups")]
        private InputList<Inputs.NexusRepositoryMavenHostedCleanupGetArgs>? _cleanups;

        /// <summary>
        /// Cleanup policies
        /// </summary>
        public InputList<Inputs.NexusRepositoryMavenHostedCleanupGetArgs> Cleanups
        {
            get => _cleanups ?? (_cleanups = new InputList<Inputs.NexusRepositoryMavenHostedCleanupGetArgs>());
            set => _cleanups = value;
        }

        /// <summary>
        /// Component configuration for the hosted repository
        /// </summary>
        [Input("component")]
        public Input<Inputs.NexusRepositoryMavenHostedComponentGetArgs>? Component { get; set; }

        /// <summary>
        /// Maven contains additional data of maven repository
        /// </summary>
        [Input("maven")]
        public Input<Inputs.NexusRepositoryMavenHostedMavenGetArgs>? Maven { get; set; }

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Input("online")]
        public Input<bool>? Online { get; set; }

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Input("storage")]
        public Input<Inputs.NexusRepositoryMavenHostedStorageGetArgs>? Storage { get; set; }

        public NexusRepositoryMavenHostedState()
        {
        }
    }
}
