// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    [NexusResourceType("nexus:index/nexusSecurityUser:NexusSecurityUser")]
    public partial class NexusSecurityUser : Pulumi.CustomResource
    {
        /// <summary>
        /// The email address associated with the user.
        /// </summary>
        [Output("email")]
        public Output<string> Email { get; private set; } = null!;

        /// <summary>
        /// The first name of the user.
        /// </summary>
        [Output("firstname")]
        public Output<string> Firstname { get; private set; } = null!;

        /// <summary>
        /// The last name of the user.
        /// </summary>
        [Output("lastname")]
        public Output<string> Lastname { get; private set; } = null!;

        /// <summary>
        /// The password for the user.
        /// </summary>
        [Output("password")]
        public Output<string> Password { get; private set; } = null!;

        /// <summary>
        /// The roles which the user has been assigned within Nexus.
        /// </summary>
        [Output("roles")]
        public Output<ImmutableArray<string>> Roles { get; private set; } = null!;

        /// <summary>
        /// The user's status, e.g. active or disabled.
        /// </summary>
        [Output("status")]
        public Output<string?> Status { get; private set; } = null!;

        /// <summary>
        /// The userid which is required for login. This value cannot be changed.
        /// </summary>
        [Output("userid")]
        public Output<string> Userid { get; private set; } = null!;


        /// <summary>
        /// Create a NexusSecurityUser resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NexusSecurityUser(string name, NexusSecurityUserArgs args, CustomResourceOptions? options = null)
            : base("nexus:index/nexusSecurityUser:NexusSecurityUser", name, args ?? new NexusSecurityUserArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NexusSecurityUser(string name, Input<string> id, NexusSecurityUserState? state = null, CustomResourceOptions? options = null)
            : base("nexus:index/nexusSecurityUser:NexusSecurityUser", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/SimCubeLtd/pulumi-nexus/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NexusSecurityUser resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NexusSecurityUser Get(string name, Input<string> id, NexusSecurityUserState? state = null, CustomResourceOptions? options = null)
        {
            return new NexusSecurityUser(name, id, state, options);
        }
    }

    public sealed class NexusSecurityUserArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The email address associated with the user.
        /// </summary>
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        /// <summary>
        /// The first name of the user.
        /// </summary>
        [Input("firstname", required: true)]
        public Input<string> Firstname { get; set; } = null!;

        /// <summary>
        /// The last name of the user.
        /// </summary>
        [Input("lastname", required: true)]
        public Input<string> Lastname { get; set; } = null!;

        /// <summary>
        /// The password for the user.
        /// </summary>
        [Input("password", required: true)]
        public Input<string> Password { get; set; } = null!;

        [Input("roles")]
        private InputList<string>? _roles;

        /// <summary>
        /// The roles which the user has been assigned within Nexus.
        /// </summary>
        public InputList<string> Roles
        {
            get => _roles ?? (_roles = new InputList<string>());
            set => _roles = value;
        }

        /// <summary>
        /// The user's status, e.g. active or disabled.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// The userid which is required for login. This value cannot be changed.
        /// </summary>
        [Input("userid", required: true)]
        public Input<string> Userid { get; set; } = null!;

        public NexusSecurityUserArgs()
        {
        }
    }

    public sealed class NexusSecurityUserState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The email address associated with the user.
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// The first name of the user.
        /// </summary>
        [Input("firstname")]
        public Input<string>? Firstname { get; set; }

        /// <summary>
        /// The last name of the user.
        /// </summary>
        [Input("lastname")]
        public Input<string>? Lastname { get; set; }

        /// <summary>
        /// The password for the user.
        /// </summary>
        [Input("password")]
        public Input<string>? Password { get; set; }

        [Input("roles")]
        private InputList<string>? _roles;

        /// <summary>
        /// The roles which the user has been assigned within Nexus.
        /// </summary>
        public InputList<string> Roles
        {
            get => _roles ?? (_roles = new InputList<string>());
            set => _roles = value;
        }

        /// <summary>
        /// The user's status, e.g. active or disabled.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// The userid which is required for login. This value cannot be changed.
        /// </summary>
        [Input("userid")]
        public Input<string>? Userid { get; set; }

        public NexusSecurityUserState()
        {
        }
    }
}
