// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    [NexusResourceType("nexus:index/nexusBlobstore:NexusBlobstore")]
    public partial class NexusBlobstore : Pulumi.CustomResource
    {
        /// <summary>
        /// Available space in Bytes
        /// </summary>
        [Output("availableSpaceInBytes")]
        public Output<string> AvailableSpaceInBytes { get; private set; } = null!;

        /// <summary>
        /// Count of blobs
        /// </summary>
        [Output("blobCount")]
        public Output<int> BlobCount { get; private set; } = null!;

        /// <summary>
        /// The S3 bucket configuration. Needed for blobstore type 'S3'
        /// </summary>
        [Output("bucketConfiguration")]
        public Output<Outputs.NexusBlobstoreBucketConfiguration?> BucketConfiguration { get; private set; } = null!;

        /// <summary>
        /// Blobstore name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The path to the blobstore contents. This can be an absolute path to anywhere on the system nxrm has access to or it can
        /// be a path relative to the sonatype-work directory
        /// </summary>
        [Output("path")]
        public Output<string?> Path { get; private set; } = null!;

        /// <summary>
        /// Soft quota of the blobstore
        /// </summary>
        [Output("softQuota")]
        public Output<Outputs.NexusBlobstoreSoftQuota?> SoftQuota { get; private set; } = null!;

        /// <summary>
        /// The total size of the blobstore in Bytes
        /// </summary>
        [Output("totalSizeInBytes")]
        public Output<int> TotalSizeInBytes { get; private set; } = null!;

        /// <summary>
        /// The type of the blobstore. Possible values: `S3` or `File`
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a NexusBlobstore resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NexusBlobstore(string name, NexusBlobstoreArgs args, CustomResourceOptions? options = null)
            : base("nexus:index/nexusBlobstore:NexusBlobstore", name, args ?? new NexusBlobstoreArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NexusBlobstore(string name, Input<string> id, NexusBlobstoreState? state = null, CustomResourceOptions? options = null)
            : base("nexus:index/nexusBlobstore:NexusBlobstore", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/SimCubeLtd/pulumi-nexus/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NexusBlobstore resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NexusBlobstore Get(string name, Input<string> id, NexusBlobstoreState? state = null, CustomResourceOptions? options = null)
        {
            return new NexusBlobstore(name, id, state, options);
        }
    }

    public sealed class NexusBlobstoreArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The S3 bucket configuration. Needed for blobstore type 'S3'
        /// </summary>
        [Input("bucketConfiguration")]
        public Input<Inputs.NexusBlobstoreBucketConfigurationArgs>? BucketConfiguration { get; set; }

        /// <summary>
        /// Blobstore name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The path to the blobstore contents. This can be an absolute path to anywhere on the system nxrm has access to or it can
        /// be a path relative to the sonatype-work directory
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// Soft quota of the blobstore
        /// </summary>
        [Input("softQuota")]
        public Input<Inputs.NexusBlobstoreSoftQuotaArgs>? SoftQuota { get; set; }

        /// <summary>
        /// The type of the blobstore. Possible values: `S3` or `File`
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public NexusBlobstoreArgs()
        {
        }
    }

    public sealed class NexusBlobstoreState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Available space in Bytes
        /// </summary>
        [Input("availableSpaceInBytes")]
        public Input<string>? AvailableSpaceInBytes { get; set; }

        /// <summary>
        /// Count of blobs
        /// </summary>
        [Input("blobCount")]
        public Input<int>? BlobCount { get; set; }

        /// <summary>
        /// The S3 bucket configuration. Needed for blobstore type 'S3'
        /// </summary>
        [Input("bucketConfiguration")]
        public Input<Inputs.NexusBlobstoreBucketConfigurationGetArgs>? BucketConfiguration { get; set; }

        /// <summary>
        /// Blobstore name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The path to the blobstore contents. This can be an absolute path to anywhere on the system nxrm has access to or it can
        /// be a path relative to the sonatype-work directory
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// Soft quota of the blobstore
        /// </summary>
        [Input("softQuota")]
        public Input<Inputs.NexusBlobstoreSoftQuotaGetArgs>? SoftQuota { get; set; }

        /// <summary>
        /// The total size of the blobstore in Bytes
        /// </summary>
        [Input("totalSizeInBytes")]
        public Input<int>? TotalSizeInBytes { get; set; }

        /// <summary>
        /// The type of the blobstore. Possible values: `S3` or `File`
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public NexusBlobstoreState()
        {
        }
    }
}
