// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    [NexusResourceType("nexus:index/nexusBlobstoreFile:NexusBlobstoreFile")]
    public partial class NexusBlobstoreFile : Pulumi.CustomResource
    {
        /// <summary>
        /// Available space in Bytes
        /// </summary>
        [Output("availableSpaceInBytes")]
        public Output<int> AvailableSpaceInBytes { get; private set; } = null!;

        /// <summary>
        /// Count of blobs
        /// </summary>
        [Output("blobCount")]
        public Output<int> BlobCount { get; private set; } = null!;

        /// <summary>
        /// Blobstore name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The path to the blobstore contents. This can be an absolute path to anywhere on the system nxrm has access to or it can
        /// be a path relative to the sonatype-work directory
        /// </summary>
        [Output("path")]
        public Output<string?> Path { get; private set; } = null!;

        /// <summary>
        /// Soft quota of the blobstore
        /// </summary>
        [Output("softQuota")]
        public Output<Outputs.NexusBlobstoreFileSoftQuota?> SoftQuota { get; private set; } = null!;

        /// <summary>
        /// The total size of the blobstore in Bytes
        /// </summary>
        [Output("totalSizeInBytes")]
        public Output<int> TotalSizeInBytes { get; private set; } = null!;


        /// <summary>
        /// Create a NexusBlobstoreFile resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NexusBlobstoreFile(string name, NexusBlobstoreFileArgs? args = null, CustomResourceOptions? options = null)
            : base("nexus:index/nexusBlobstoreFile:NexusBlobstoreFile", name, args ?? new NexusBlobstoreFileArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NexusBlobstoreFile(string name, Input<string> id, NexusBlobstoreFileState? state = null, CustomResourceOptions? options = null)
            : base("nexus:index/nexusBlobstoreFile:NexusBlobstoreFile", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/SimCubeLtd/pulumi-nexus/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NexusBlobstoreFile resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NexusBlobstoreFile Get(string name, Input<string> id, NexusBlobstoreFileState? state = null, CustomResourceOptions? options = null)
        {
            return new NexusBlobstoreFile(name, id, state, options);
        }
    }

    public sealed class NexusBlobstoreFileArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Blobstore name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The path to the blobstore contents. This can be an absolute path to anywhere on the system nxrm has access to or it can
        /// be a path relative to the sonatype-work directory
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// Soft quota of the blobstore
        /// </summary>
        [Input("softQuota")]
        public Input<Inputs.NexusBlobstoreFileSoftQuotaArgs>? SoftQuota { get; set; }

        public NexusBlobstoreFileArgs()
        {
        }
    }

    public sealed class NexusBlobstoreFileState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Available space in Bytes
        /// </summary>
        [Input("availableSpaceInBytes")]
        public Input<int>? AvailableSpaceInBytes { get; set; }

        /// <summary>
        /// Count of blobs
        /// </summary>
        [Input("blobCount")]
        public Input<int>? BlobCount { get; set; }

        /// <summary>
        /// Blobstore name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The path to the blobstore contents. This can be an absolute path to anywhere on the system nxrm has access to or it can
        /// be a path relative to the sonatype-work directory
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// Soft quota of the blobstore
        /// </summary>
        [Input("softQuota")]
        public Input<Inputs.NexusBlobstoreFileSoftQuotaGetArgs>? SoftQuota { get; set; }

        /// <summary>
        /// The total size of the blobstore in Bytes
        /// </summary>
        [Input("totalSizeInBytes")]
        public Input<int>? TotalSizeInBytes { get; set; }

        public NexusBlobstoreFileState()
        {
        }
    }
}
