// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    [NexusResourceType("nexus:index/nexusRepositoryDockerHosted:NexusRepositoryDockerHosted")]
    public partial class NexusRepositoryDockerHosted : Pulumi.CustomResource
    {
        /// <summary>
        /// Cleanup policies
        /// </summary>
        [Output("cleanups")]
        public Output<ImmutableArray<Outputs.NexusRepositoryDockerHostedCleanup>> Cleanups { get; private set; } = null!;

        /// <summary>
        /// Component configuration for the hosted repository
        /// </summary>
        [Output("component")]
        public Output<Outputs.NexusRepositoryDockerHostedComponent> Component { get; private set; } = null!;

        /// <summary>
        /// docker contains the configuration of the docker repository
        /// </summary>
        [Output("docker")]
        public Output<Outputs.NexusRepositoryDockerHostedDocker> Docker { get; private set; } = null!;

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Output("online")]
        public Output<bool?> Online { get; private set; } = null!;

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Output("storage")]
        public Output<Outputs.NexusRepositoryDockerHostedStorage> Storage { get; private set; } = null!;


        /// <summary>
        /// Create a NexusRepositoryDockerHosted resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NexusRepositoryDockerHosted(string name, NexusRepositoryDockerHostedArgs args, CustomResourceOptions? options = null)
            : base("nexus:index/nexusRepositoryDockerHosted:NexusRepositoryDockerHosted", name, args ?? new NexusRepositoryDockerHostedArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NexusRepositoryDockerHosted(string name, Input<string> id, NexusRepositoryDockerHostedState? state = null, CustomResourceOptions? options = null)
            : base("nexus:index/nexusRepositoryDockerHosted:NexusRepositoryDockerHosted", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/SimCubeLtd/pulumi-nexus/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NexusRepositoryDockerHosted resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NexusRepositoryDockerHosted Get(string name, Input<string> id, NexusRepositoryDockerHostedState? state = null, CustomResourceOptions? options = null)
        {
            return new NexusRepositoryDockerHosted(name, id, state, options);
        }
    }

    public sealed class NexusRepositoryDockerHostedArgs : Pulumi.ResourceArgs
    {
        [Input("cleanups")]
        private InputList<Inputs.NexusRepositoryDockerHostedCleanupArgs>? _cleanups;

        /// <summary>
        /// Cleanup policies
        /// </summary>
        public InputList<Inputs.NexusRepositoryDockerHostedCleanupArgs> Cleanups
        {
            get => _cleanups ?? (_cleanups = new InputList<Inputs.NexusRepositoryDockerHostedCleanupArgs>());
            set => _cleanups = value;
        }

        /// <summary>
        /// Component configuration for the hosted repository
        /// </summary>
        [Input("component")]
        public Input<Inputs.NexusRepositoryDockerHostedComponentArgs>? Component { get; set; }

        /// <summary>
        /// docker contains the configuration of the docker repository
        /// </summary>
        [Input("docker", required: true)]
        public Input<Inputs.NexusRepositoryDockerHostedDockerArgs> Docker { get; set; } = null!;

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Input("online")]
        public Input<bool>? Online { get; set; }

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Input("storage", required: true)]
        public Input<Inputs.NexusRepositoryDockerHostedStorageArgs> Storage { get; set; } = null!;

        public NexusRepositoryDockerHostedArgs()
        {
        }
    }

    public sealed class NexusRepositoryDockerHostedState : Pulumi.ResourceArgs
    {
        [Input("cleanups")]
        private InputList<Inputs.NexusRepositoryDockerHostedCleanupGetArgs>? _cleanups;

        /// <summary>
        /// Cleanup policies
        /// </summary>
        public InputList<Inputs.NexusRepositoryDockerHostedCleanupGetArgs> Cleanups
        {
            get => _cleanups ?? (_cleanups = new InputList<Inputs.NexusRepositoryDockerHostedCleanupGetArgs>());
            set => _cleanups = value;
        }

        /// <summary>
        /// Component configuration for the hosted repository
        /// </summary>
        [Input("component")]
        public Input<Inputs.NexusRepositoryDockerHostedComponentGetArgs>? Component { get; set; }

        /// <summary>
        /// docker contains the configuration of the docker repository
        /// </summary>
        [Input("docker")]
        public Input<Inputs.NexusRepositoryDockerHostedDockerGetArgs>? Docker { get; set; }

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Input("online")]
        public Input<bool>? Online { get; set; }

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Input("storage")]
        public Input<Inputs.NexusRepositoryDockerHostedStorageGetArgs>? Storage { get; set; }

        public NexusRepositoryDockerHostedState()
        {
        }
    }
}
