// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    [NexusResourceType("nexus:index/nexusRepositoryYumGroup:NexusRepositoryYumGroup")]
    public partial class NexusRepositoryYumGroup : Pulumi.CustomResource
    {
        /// <summary>
        /// Configuration for repository group
        /// </summary>
        [Output("group")]
        public Output<Outputs.NexusRepositoryYumGroupGroup> Group { get; private set; } = null!;

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Output("online")]
        public Output<bool?> Online { get; private set; } = null!;

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Output("storage")]
        public Output<Outputs.NexusRepositoryYumGroupStorage> Storage { get; private set; } = null!;

        /// <summary>
        /// Contains signing data of repositores
        /// </summary>
        [Output("yumSigning")]
        public Output<Outputs.NexusRepositoryYumGroupYumSigning?> YumSigning { get; private set; } = null!;


        /// <summary>
        /// Create a NexusRepositoryYumGroup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NexusRepositoryYumGroup(string name, NexusRepositoryYumGroupArgs args, CustomResourceOptions? options = null)
            : base("nexus:index/nexusRepositoryYumGroup:NexusRepositoryYumGroup", name, args ?? new NexusRepositoryYumGroupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NexusRepositoryYumGroup(string name, Input<string> id, NexusRepositoryYumGroupState? state = null, CustomResourceOptions? options = null)
            : base("nexus:index/nexusRepositoryYumGroup:NexusRepositoryYumGroup", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/SimCubeLtd/pulumi-nexus/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NexusRepositoryYumGroup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NexusRepositoryYumGroup Get(string name, Input<string> id, NexusRepositoryYumGroupState? state = null, CustomResourceOptions? options = null)
        {
            return new NexusRepositoryYumGroup(name, id, state, options);
        }
    }

    public sealed class NexusRepositoryYumGroupArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration for repository group
        /// </summary>
        [Input("group", required: true)]
        public Input<Inputs.NexusRepositoryYumGroupGroupArgs> Group { get; set; } = null!;

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Input("online")]
        public Input<bool>? Online { get; set; }

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Input("storage", required: true)]
        public Input<Inputs.NexusRepositoryYumGroupStorageArgs> Storage { get; set; } = null!;

        /// <summary>
        /// Contains signing data of repositores
        /// </summary>
        [Input("yumSigning")]
        public Input<Inputs.NexusRepositoryYumGroupYumSigningArgs>? YumSigning { get; set; }

        public NexusRepositoryYumGroupArgs()
        {
        }
    }

    public sealed class NexusRepositoryYumGroupState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration for repository group
        /// </summary>
        [Input("group")]
        public Input<Inputs.NexusRepositoryYumGroupGroupGetArgs>? Group { get; set; }

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Input("online")]
        public Input<bool>? Online { get; set; }

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Input("storage")]
        public Input<Inputs.NexusRepositoryYumGroupStorageGetArgs>? Storage { get; set; }

        /// <summary>
        /// Contains signing data of repositores
        /// </summary>
        [Input("yumSigning")]
        public Input<Inputs.NexusRepositoryYumGroupYumSigningGetArgs>? YumSigning { get; set; }

        public NexusRepositoryYumGroupState()
        {
        }
    }
}
