// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    [NexusResourceType("nexus:index/nexusAnonymous:NexusAnonymous")]
    public partial class NexusAnonymous : Pulumi.CustomResource
    {
        /// <summary>
        /// Activate the anonymous access to the repository manager. Default: false
        /// </summary>
        [Output("enabled")]
        public Output<bool?> Enabled { get; private set; } = null!;

        /// <summary>
        /// The name of the used realm. Default: "NexusAuthorizingRealm"
        /// </summary>
        [Output("realmName")]
        public Output<string?> RealmName { get; private set; } = null!;

        /// <summary>
        /// The user id used by anonymous access. Default: "anonymous"
        /// </summary>
        [Output("userId")]
        public Output<string?> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a NexusAnonymous resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NexusAnonymous(string name, NexusAnonymousArgs? args = null, CustomResourceOptions? options = null)
            : base("nexus:index/nexusAnonymous:NexusAnonymous", name, args ?? new NexusAnonymousArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NexusAnonymous(string name, Input<string> id, NexusAnonymousState? state = null, CustomResourceOptions? options = null)
            : base("nexus:index/nexusAnonymous:NexusAnonymous", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/SimCubeLtd/pulumi-nexus/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NexusAnonymous resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NexusAnonymous Get(string name, Input<string> id, NexusAnonymousState? state = null, CustomResourceOptions? options = null)
        {
            return new NexusAnonymous(name, id, state, options);
        }
    }

    public sealed class NexusAnonymousArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Activate the anonymous access to the repository manager. Default: false
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The name of the used realm. Default: "NexusAuthorizingRealm"
        /// </summary>
        [Input("realmName")]
        public Input<string>? RealmName { get; set; }

        /// <summary>
        /// The user id used by anonymous access. Default: "anonymous"
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public NexusAnonymousArgs()
        {
        }
    }

    public sealed class NexusAnonymousState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Activate the anonymous access to the repository manager. Default: false
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The name of the used realm. Default: "NexusAuthorizingRealm"
        /// </summary>
        [Input("realmName")]
        public Input<string>? RealmName { get; set; }

        /// <summary>
        /// The user id used by anonymous access. Default: "anonymous"
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public NexusAnonymousState()
        {
        }
    }
}
