// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    [NexusResourceType("nexus:index/nexusRepositoryDockerProxy:NexusRepositoryDockerProxy")]
    public partial class NexusRepositoryDockerProxy : Pulumi.CustomResource
    {
        /// <summary>
        /// Cleanup policies
        /// </summary>
        [Output("cleanups")]
        public Output<ImmutableArray<Outputs.NexusRepositoryDockerProxyCleanup>> Cleanups { get; private set; } = null!;

        /// <summary>
        /// docker contains the configuration of the docker repository
        /// </summary>
        [Output("docker")]
        public Output<Outputs.NexusRepositoryDockerProxyDocker> Docker { get; private set; } = null!;

        /// <summary>
        /// docker_proxy contains the configuration of the docker index
        /// </summary>
        [Output("dockerProxy")]
        public Output<Outputs.NexusRepositoryDockerProxyDockerProxy> DockerProxy { get; private set; } = null!;

        /// <summary>
        /// HTTP Client configuration for proxy repositories. Required for docker proxy repositories
        /// </summary>
        [Output("httpClient")]
        public Output<Outputs.NexusRepositoryDockerProxyHttpClient?> HttpClient { get; private set; } = null!;

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Configuration of the negative cache handling
        /// </summary>
        [Output("negativeCache")]
        public Output<Outputs.NexusRepositoryDockerProxyNegativeCache?> NegativeCache { get; private set; } = null!;

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Output("online")]
        public Output<bool?> Online { get; private set; } = null!;

        /// <summary>
        /// Configuration for the proxy repository
        /// </summary>
        [Output("proxy")]
        public Output<Outputs.NexusRepositoryDockerProxyProxy> Proxy { get; private set; } = null!;

        /// <summary>
        /// The name of the routing rule assigned to this repository
        /// </summary>
        [Output("routingRule")]
        public Output<string?> RoutingRule { get; private set; } = null!;

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Output("storage")]
        public Output<Outputs.NexusRepositoryDockerProxyStorage> Storage { get; private set; } = null!;


        /// <summary>
        /// Create a NexusRepositoryDockerProxy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NexusRepositoryDockerProxy(string name, NexusRepositoryDockerProxyArgs args, CustomResourceOptions? options = null)
            : base("nexus:index/nexusRepositoryDockerProxy:NexusRepositoryDockerProxy", name, args ?? new NexusRepositoryDockerProxyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NexusRepositoryDockerProxy(string name, Input<string> id, NexusRepositoryDockerProxyState? state = null, CustomResourceOptions? options = null)
            : base("nexus:index/nexusRepositoryDockerProxy:NexusRepositoryDockerProxy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/SimCubeLtd/pulumi-nexus/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NexusRepositoryDockerProxy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NexusRepositoryDockerProxy Get(string name, Input<string> id, NexusRepositoryDockerProxyState? state = null, CustomResourceOptions? options = null)
        {
            return new NexusRepositoryDockerProxy(name, id, state, options);
        }
    }

    public sealed class NexusRepositoryDockerProxyArgs : Pulumi.ResourceArgs
    {
        [Input("cleanups")]
        private InputList<Inputs.NexusRepositoryDockerProxyCleanupArgs>? _cleanups;

        /// <summary>
        /// Cleanup policies
        /// </summary>
        public InputList<Inputs.NexusRepositoryDockerProxyCleanupArgs> Cleanups
        {
            get => _cleanups ?? (_cleanups = new InputList<Inputs.NexusRepositoryDockerProxyCleanupArgs>());
            set => _cleanups = value;
        }

        /// <summary>
        /// docker contains the configuration of the docker repository
        /// </summary>
        [Input("docker", required: true)]
        public Input<Inputs.NexusRepositoryDockerProxyDockerArgs> Docker { get; set; } = null!;

        /// <summary>
        /// docker_proxy contains the configuration of the docker index
        /// </summary>
        [Input("dockerProxy", required: true)]
        public Input<Inputs.NexusRepositoryDockerProxyDockerProxyArgs> DockerProxy { get; set; } = null!;

        /// <summary>
        /// HTTP Client configuration for proxy repositories. Required for docker proxy repositories
        /// </summary>
        [Input("httpClient")]
        public Input<Inputs.NexusRepositoryDockerProxyHttpClientArgs>? HttpClient { get; set; }

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Configuration of the negative cache handling
        /// </summary>
        [Input("negativeCache")]
        public Input<Inputs.NexusRepositoryDockerProxyNegativeCacheArgs>? NegativeCache { get; set; }

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Input("online")]
        public Input<bool>? Online { get; set; }

        /// <summary>
        /// Configuration for the proxy repository
        /// </summary>
        [Input("proxy", required: true)]
        public Input<Inputs.NexusRepositoryDockerProxyProxyArgs> Proxy { get; set; } = null!;

        /// <summary>
        /// The name of the routing rule assigned to this repository
        /// </summary>
        [Input("routingRule")]
        public Input<string>? RoutingRule { get; set; }

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Input("storage", required: true)]
        public Input<Inputs.NexusRepositoryDockerProxyStorageArgs> Storage { get; set; } = null!;

        public NexusRepositoryDockerProxyArgs()
        {
        }
    }

    public sealed class NexusRepositoryDockerProxyState : Pulumi.ResourceArgs
    {
        [Input("cleanups")]
        private InputList<Inputs.NexusRepositoryDockerProxyCleanupGetArgs>? _cleanups;

        /// <summary>
        /// Cleanup policies
        /// </summary>
        public InputList<Inputs.NexusRepositoryDockerProxyCleanupGetArgs> Cleanups
        {
            get => _cleanups ?? (_cleanups = new InputList<Inputs.NexusRepositoryDockerProxyCleanupGetArgs>());
            set => _cleanups = value;
        }

        /// <summary>
        /// docker contains the configuration of the docker repository
        /// </summary>
        [Input("docker")]
        public Input<Inputs.NexusRepositoryDockerProxyDockerGetArgs>? Docker { get; set; }

        /// <summary>
        /// docker_proxy contains the configuration of the docker index
        /// </summary>
        [Input("dockerProxy")]
        public Input<Inputs.NexusRepositoryDockerProxyDockerProxyGetArgs>? DockerProxy { get; set; }

        /// <summary>
        /// HTTP Client configuration for proxy repositories. Required for docker proxy repositories
        /// </summary>
        [Input("httpClient")]
        public Input<Inputs.NexusRepositoryDockerProxyHttpClientGetArgs>? HttpClient { get; set; }

        /// <summary>
        /// A unique identifier for this repository
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Configuration of the negative cache handling
        /// </summary>
        [Input("negativeCache")]
        public Input<Inputs.NexusRepositoryDockerProxyNegativeCacheGetArgs>? NegativeCache { get; set; }

        /// <summary>
        /// Whether this repository accepts incoming requests
        /// </summary>
        [Input("online")]
        public Input<bool>? Online { get; set; }

        /// <summary>
        /// Configuration for the proxy repository
        /// </summary>
        [Input("proxy")]
        public Input<Inputs.NexusRepositoryDockerProxyProxyGetArgs>? Proxy { get; set; }

        /// <summary>
        /// The name of the routing rule assigned to this repository
        /// </summary>
        [Input("routingRule")]
        public Input<string>? RoutingRule { get; set; }

        /// <summary>
        /// The storage configuration of the repository
        /// </summary>
        [Input("storage")]
        public Input<Inputs.NexusRepositoryDockerProxyStorageGetArgs>? Storage { get; set; }

        public NexusRepositoryDockerProxyState()
        {
        }
    }
}
