// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus
{
    [NexusResourceType("nexus:index/nexusSecurityContentSelector:NexusSecurityContentSelector")]
    public partial class NexusSecurityContentSelector : Pulumi.CustomResource
    {
        /// <summary>
        /// A description of the content selector
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The content selector expression
        /// </summary>
        [Output("expression")]
        public Output<string> Expression { get; private set; } = null!;

        /// <summary>
        /// Content selector name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a NexusSecurityContentSelector resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NexusSecurityContentSelector(string name, NexusSecurityContentSelectorArgs args, CustomResourceOptions? options = null)
            : base("nexus:index/nexusSecurityContentSelector:NexusSecurityContentSelector", name, args ?? new NexusSecurityContentSelectorArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NexusSecurityContentSelector(string name, Input<string> id, NexusSecurityContentSelectorState? state = null, CustomResourceOptions? options = null)
            : base("nexus:index/nexusSecurityContentSelector:NexusSecurityContentSelector", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/SimCubeLtd/pulumi-nexus/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NexusSecurityContentSelector resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NexusSecurityContentSelector Get(string name, Input<string> id, NexusSecurityContentSelectorState? state = null, CustomResourceOptions? options = null)
        {
            return new NexusSecurityContentSelector(name, id, state, options);
        }
    }

    public sealed class NexusSecurityContentSelectorArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// A description of the content selector
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The content selector expression
        /// </summary>
        [Input("expression", required: true)]
        public Input<string> Expression { get; set; } = null!;

        /// <summary>
        /// Content selector name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public NexusSecurityContentSelectorArgs()
        {
        }
    }

    public sealed class NexusSecurityContentSelectorState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// A description of the content selector
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The content selector expression
        /// </summary>
        [Input("expression")]
        public Input<string>? Expression { get; set; }

        /// <summary>
        /// Content selector name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public NexusSecurityContentSelectorState()
        {
        }
    }
}
