// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Boolean to specify wether insecure SSL connections are allowed or not. Reading environment variable
// NEXUS_INSECURE_SKIP_VERIFY. Default:`true`
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "nexus:insecure")
}

// Password of user to connect to API. Reading environment variable NEXUS_PASSWORD. Default:`admin123`
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "nexus:password")
}

// URL of Nexus to reach API. Reading environment variable NEXUS_URL. Default:`http://127.0.0.1:8080`
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "nexus:url")
}

// Username used to connect to API. Reading environment variable NEXUS_USERNAME. Default:`admin`
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "nexus:username")
}
