// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus.Outputs
{

    [OutputType]
    public sealed class GetNexusBlobstoreAzureBucketConfigurationResult
    {
        public readonly string AccountName;
        public readonly ImmutableArray<Outputs.GetNexusBlobstoreAzureBucketConfigurationAuthenticationResult> Authentications;
        public readonly string ContainerName;

        [OutputConstructor]
        private GetNexusBlobstoreAzureBucketConfigurationResult(
            string accountName,

            ImmutableArray<Outputs.GetNexusBlobstoreAzureBucketConfigurationAuthenticationResult> authentications,

            string containerName)
        {
            AccountName = accountName;
            Authentications = authentications;
            ContainerName = containerName;
        }
    }
}
