// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus.Outputs
{

    [OutputType]
    public sealed class GetNexusBlobstoreS3BucketConfigurationResult
    {
        public readonly ImmutableArray<Outputs.GetNexusBlobstoreS3BucketConfigurationAdvancedBucketConnectionResult> AdvancedBucketConnections;
        public readonly ImmutableArray<Outputs.GetNexusBlobstoreS3BucketConfigurationBucketSecurityResult> BucketSecurities;
        public readonly ImmutableArray<Outputs.GetNexusBlobstoreS3BucketConfigurationBucketResult> Buckets;
        public readonly ImmutableArray<Outputs.GetNexusBlobstoreS3BucketConfigurationEncryptionResult> Encryptions;

        [OutputConstructor]
        private GetNexusBlobstoreS3BucketConfigurationResult(
            ImmutableArray<Outputs.GetNexusBlobstoreS3BucketConfigurationAdvancedBucketConnectionResult> advancedBucketConnections,

            ImmutableArray<Outputs.GetNexusBlobstoreS3BucketConfigurationBucketSecurityResult> bucketSecurities,

            ImmutableArray<Outputs.GetNexusBlobstoreS3BucketConfigurationBucketResult> buckets,

            ImmutableArray<Outputs.GetNexusBlobstoreS3BucketConfigurationEncryptionResult> encryptions)
        {
            AdvancedBucketConnections = advancedBucketConnections;
            BucketSecurities = bucketSecurities;
            Buckets = buckets;
            Encryptions = encryptions;
        }
    }
}
