// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus.Outputs
{

    [OutputType]
    public sealed class GetNexusRepositoryAptProxyHttpClientResult
    {
        public readonly ImmutableArray<Outputs.GetNexusRepositoryAptProxyHttpClientAuthenticationResult> Authentications;
        public readonly bool AutoBlock;
        public readonly bool Blocked;
        public readonly ImmutableArray<Outputs.GetNexusRepositoryAptProxyHttpClientConnectionResult> Connections;

        [OutputConstructor]
        private GetNexusRepositoryAptProxyHttpClientResult(
            ImmutableArray<Outputs.GetNexusRepositoryAptProxyHttpClientAuthenticationResult> authentications,

            bool autoBlock,

            bool blocked,

            ImmutableArray<Outputs.GetNexusRepositoryAptProxyHttpClientConnectionResult> connections)
        {
            Authentications = authentications;
            AutoBlock = autoBlock;
            Blocked = blocked;
            Connections = connections;
        }
    }
}
