// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus.Outputs
{

    [OutputType]
    public sealed class NexusRepositoryYumProxyHttpClient
    {
        public readonly Outputs.NexusRepositoryYumProxyHttpClientAuthentication? Authentication;
        public readonly bool? AutoBlock;
        public readonly bool? Blocked;
        public readonly Outputs.NexusRepositoryYumProxyHttpClientConnection? Connection;

        [OutputConstructor]
        private NexusRepositoryYumProxyHttpClient(
            Outputs.NexusRepositoryYumProxyHttpClientAuthentication? authentication,

            bool? autoBlock,

            bool? blocked,

            Outputs.NexusRepositoryYumProxyHttpClientConnection? connection)
        {
            Authentication = authentication;
            AutoBlock = autoBlock;
            Blocked = blocked;
            Connection = connection;
        }
    }
}
