// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus.Outputs
{

    [OutputType]
    public sealed class NexusBlobstoreS3BucketConfigurationAdvancedBucketConnection
    {
        public readonly string? Endpoint;
        public readonly bool? ForcePathStyle;
        public readonly int? MaxConnectionPoolSize;
        public readonly string? SignerType;

        [OutputConstructor]
        private NexusBlobstoreS3BucketConfigurationAdvancedBucketConnection(
            string? endpoint,

            bool? forcePathStyle,

            int? maxConnectionPoolSize,

            string? signerType)
        {
            Endpoint = endpoint;
            ForcePathStyle = forcePathStyle;
            MaxConnectionPoolSize = maxConnectionPoolSize;
            SignerType = signerType;
        }
    }
}
