// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus.Inputs
{

    public sealed class GetNexusBlobstoreBucketConfigurationBucketSecurityArgs : Pulumi.InvokeArgs
    {
        [Input("accessKeyId", required: true)]
        public string AccessKeyId { get; set; } = null!;

        [Input("role")]
        public string? Role { get; set; }

        [Input("secretAccessKey", required: true)]
        public string SecretAccessKey { get; set; } = null!;

        [Input("sessionToken")]
        public string? SessionToken { get; set; }

        public GetNexusBlobstoreBucketConfigurationBucketSecurityArgs()
        {
        }
    }
}
