// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus.Inputs
{

    public sealed class GetNexusBlobstoreBucketConfigurationBucketArgs : Pulumi.InvokeArgs
    {
        [Input("expiration")]
        public int? Expiration { get; set; }

        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("prefix")]
        public string? Prefix { get; set; }

        [Input("region", required: true)]
        public string Region { get; set; } = null!;

        public GetNexusBlobstoreBucketConfigurationBucketArgs()
        {
        }
    }
}
