// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus.Inputs
{

    public sealed class NexusBlobstoreBucketConfigurationGetArgs : Pulumi.ResourceArgs
    {
        [Input("advancedBucketConnection")]
        public Input<Inputs.NexusBlobstoreBucketConfigurationAdvancedBucketConnectionGetArgs>? AdvancedBucketConnection { get; set; }

        [Input("bucket", required: true)]
        public Input<Inputs.NexusBlobstoreBucketConfigurationBucketGetArgs> Bucket { get; set; } = null!;

        [Input("bucketSecurity")]
        public Input<Inputs.NexusBlobstoreBucketConfigurationBucketSecurityGetArgs>? BucketSecurity { get; set; }

        [Input("encryption")]
        public Input<Inputs.NexusBlobstoreBucketConfigurationEncryptionGetArgs>? Encryption { get; set; }

        public NexusBlobstoreBucketConfigurationGetArgs()
        {
        }
    }
}
