// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nexus.Inputs
{

    public sealed class NexusRepositoryYumGroupYumSigningArgs : Pulumi.ResourceArgs
    {
        [Input("keypair", required: true)]
        public Input<string> Keypair { get; set; } = null!;

        [Input("passphrase")]
        public Input<string>? Passphrase { get; set; }

        public NexusRepositoryYumGroupYumSigningArgs()
        {
        }
    }
}
