// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getNexusRepositoryYumHosted(args: GetNexusRepositoryYumHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetNexusRepositoryYumHostedResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("nexus:index/getNexusRepositoryYumHosted:GetNexusRepositoryYumHosted", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking GetNexusRepositoryYumHosted.
 */
export interface GetNexusRepositoryYumHostedArgs {
    name: string;
}

/**
 * A collection of values returned by GetNexusRepositoryYumHosted.
 */
export interface GetNexusRepositoryYumHostedResult {
    readonly cleanups: outputs.GetNexusRepositoryYumHostedCleanup[];
    readonly components: outputs.GetNexusRepositoryYumHostedComponent[];
    readonly deployPolicy: string;
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly repodataDepth: number;
    readonly storages: outputs.GetNexusRepositoryYumHostedStorage[];
}

export function getNexusRepositoryYumHostedOutput(args: GetNexusRepositoryYumHostedOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNexusRepositoryYumHostedResult> {
    return pulumi.output(args).apply(a => getNexusRepositoryYumHosted(a, opts))
}

/**
 * A collection of arguments for invoking GetNexusRepositoryYumHosted.
 */
export interface GetNexusRepositoryYumHostedOutputArgs {
    name: pulumi.Input<string>;
}
