// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getNexusRepositoryYumGroup(args: GetNexusRepositoryYumGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetNexusRepositoryYumGroupResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("nexus:index/getNexusRepositoryYumGroup:GetNexusRepositoryYumGroup", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking GetNexusRepositoryYumGroup.
 */
export interface GetNexusRepositoryYumGroupArgs {
    name: string;
}

/**
 * A collection of values returned by GetNexusRepositoryYumGroup.
 */
export interface GetNexusRepositoryYumGroupResult {
    readonly groups: outputs.GetNexusRepositoryYumGroupGroup[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetNexusRepositoryYumGroupStorage[];
    readonly yumSignings: outputs.GetNexusRepositoryYumGroupYumSigning[];
}

export function getNexusRepositoryYumGroupOutput(args: GetNexusRepositoryYumGroupOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNexusRepositoryYumGroupResult> {
    return pulumi.output(args).apply(a => getNexusRepositoryYumGroup(a, opts))
}

/**
 * A collection of arguments for invoking GetNexusRepositoryYumGroup.
 */
export interface GetNexusRepositoryYumGroupOutputArgs {
    name: pulumi.Input<string>;
}
