// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getNexusBlobstoreS3(args: GetNexusBlobstoreS3Args, opts?: pulumi.InvokeOptions): Promise<GetNexusBlobstoreS3Result> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("nexus:index/getNexusBlobstoreS3:GetNexusBlobstoreS3", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking GetNexusBlobstoreS3.
 */
export interface GetNexusBlobstoreS3Args {
    name: string;
}

/**
 * A collection of values returned by GetNexusBlobstoreS3.
 */
export interface GetNexusBlobstoreS3Result {
    readonly blobCount: number;
    readonly bucketConfigurations: outputs.GetNexusBlobstoreS3BucketConfiguration[];
    readonly id: string;
    readonly name: string;
    readonly softQuotas: outputs.GetNexusBlobstoreS3SoftQuota[];
    readonly totalSizeInBytes: number;
}

export function getNexusBlobstoreS3Output(args: GetNexusBlobstoreS3OutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNexusBlobstoreS3Result> {
    return pulumi.output(args).apply(a => getNexusBlobstoreS3(a, opts))
}

/**
 * A collection of arguments for invoking GetNexusBlobstoreS3.
 */
export interface GetNexusBlobstoreS3OutputArgs {
    name: pulumi.Input<string>;
}
