// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getNexusRepositoryList(opts?: pulumi.InvokeOptions): Promise<GetNexusRepositoryListResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("nexus:index/getNexusRepositoryList:GetNexusRepositoryList", {
    }, opts);
}

/**
 * A collection of values returned by GetNexusRepositoryList.
 */
export interface GetNexusRepositoryListResult {
    readonly id: string;
    readonly items: outputs.GetNexusRepositoryListItem[];
}
