// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getNexusBlobstoreGroup(args: GetNexusBlobstoreGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetNexusBlobstoreGroupResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("nexus:index/getNexusBlobstoreGroup:GetNexusBlobstoreGroup", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking GetNexusBlobstoreGroup.
 */
export interface GetNexusBlobstoreGroupArgs {
    name: string;
}

/**
 * A collection of values returned by GetNexusBlobstoreGroup.
 */
export interface GetNexusBlobstoreGroupResult {
    readonly availableSpaceInBytes: number;
    readonly blobCount: number;
    readonly fillPolicy: string;
    readonly id: string;
    readonly members: string[];
    readonly name: string;
    readonly softQuotas: outputs.GetNexusBlobstoreGroupSoftQuota[];
    readonly totalSizeInBytes: number;
}

export function getNexusBlobstoreGroupOutput(args: GetNexusBlobstoreGroupOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNexusBlobstoreGroupResult> {
    return pulumi.output(args).apply(a => getNexusBlobstoreGroup(a, opts))
}

/**
 * A collection of arguments for invoking GetNexusBlobstoreGroup.
 */
export interface GetNexusBlobstoreGroupOutputArgs {
    name: pulumi.Input<string>;
}
