// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNexusSecurityAnonymous(opts?: pulumi.InvokeOptions): Promise<GetNexusSecurityAnonymousResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("nexus:index/getNexusSecurityAnonymous:GetNexusSecurityAnonymous", {
    }, opts);
}

/**
 * A collection of values returned by GetNexusSecurityAnonymous.
 */
export interface GetNexusSecurityAnonymousResult {
    readonly enabled: boolean;
    readonly id: string;
    readonly realmName: string;
    readonly userId: string;
}
