// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getNexusRepositoryYumProxy(args: GetNexusRepositoryYumProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetNexusRepositoryYumProxyResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("nexus:index/getNexusRepositoryYumProxy:GetNexusRepositoryYumProxy", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking GetNexusRepositoryYumProxy.
 */
export interface GetNexusRepositoryYumProxyArgs {
    name: string;
}

/**
 * A collection of values returned by GetNexusRepositoryYumProxy.
 */
export interface GetNexusRepositoryYumProxyResult {
    readonly cleanups: outputs.GetNexusRepositoryYumProxyCleanup[];
    readonly httpClients: outputs.GetNexusRepositoryYumProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetNexusRepositoryYumProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetNexusRepositoryYumProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetNexusRepositoryYumProxyStorage[];
    readonly yumSignings: outputs.GetNexusRepositoryYumProxyYumSigning[];
}

export function getNexusRepositoryYumProxyOutput(args: GetNexusRepositoryYumProxyOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNexusRepositoryYumProxyResult> {
    return pulumi.output(args).apply(a => getNexusRepositoryYumProxy(a, opts))
}

/**
 * A collection of arguments for invoking GetNexusRepositoryYumProxy.
 */
export interface GetNexusRepositoryYumProxyOutputArgs {
    name: pulumi.Input<string>;
}
