// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getNexusPrivileges(args?: GetNexusPrivilegesArgs, opts?: pulumi.InvokeOptions): Promise<GetNexusPrivilegesResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("nexus:index/getNexusPrivileges:GetNexusPrivileges", {
        "domain": args.domain,
        "format": args.format,
        "name": args.name,
        "repository": args.repository,
        "type": args.type,
    }, opts);
}

/**
 * A collection of arguments for invoking GetNexusPrivileges.
 */
export interface GetNexusPrivilegesArgs {
    domain?: string;
    format?: string;
    name?: string;
    repository?: string;
    type?: string;
}

/**
 * A collection of values returned by GetNexusPrivileges.
 */
export interface GetNexusPrivilegesResult {
    readonly domain?: string;
    readonly format?: string;
    readonly id: string;
    readonly name?: string;
    readonly privileges: outputs.GetNexusPrivilegesPrivilege[];
    readonly repository?: string;
    readonly type?: string;
}

export function getNexusPrivilegesOutput(args?: GetNexusPrivilegesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNexusPrivilegesResult> {
    return pulumi.output(args).apply(a => getNexusPrivileges(a, opts))
}

/**
 * A collection of arguments for invoking GetNexusPrivileges.
 */
export interface GetNexusPrivilegesOutputArgs {
    domain?: pulumi.Input<string>;
    format?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    repository?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
}
